name: build-sip003

on:
  workflow_dispatch:

env:
  UPSTREAM_URL: https://github.com/Mygod/slipstream-plugin-android
  UPSTREAM_BRANCH: master
  OPENSSL_URL: https://github.com/openssl/openssl/releases/download/openssl-3.6.0/openssl-3.6.0.tar.gz

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Build APK
        run: |

          rustup target add \
            armv7-linux-androideabi \
            aarch64-linux-android

          mkdir src
          cd src

          git clone "${UPSTREAM_URL:?}" .
          git submodule update --init --recursive

          # Disable picoquic's OpenSSL
          picoquic_cmake=$(find -ipath '*/vendor/picoquic/cmakelists.txt' | head -n1)
          sed -Ei 's|(^\s*OPTION\(WITH_OPENSSL.*\s+)ON\)\s*$|\1OFF\)|' "${picoquic_cmake:?}"

          # Fix gradle build's NDK version
          ndk_version=$(basename "${ANDROID_NDK_HOME:?}")
          sed -Ei 's|(^\s*ndkVersion\s*=\s*)"[^"]+"|\1"'"${ndk_version:?}"'"|' app/build.gradle.kts

          chmod 755 gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v7
        with:
          name: slipdroid-apk
          path: src/app/build/outputs/**/*.apk
